theme {
    # color_sheme = /usr/share/qt6ct/colors/darker.conf
    icon_theme = Papirus-Dark
    style = Adwaita-Dark
    font_fixed = Ubuntu Mono
    font_fixed_size = 12
    font = Ubuntu
    font_size = 12
}