windowrule = match:class ^(resolve)$, match:title ^(resolve)%, match:float 1, tag +davinci-splash

# Focus floating DaVinci Resolve dialog windows
windowrule = stay_focused on, match:class .*[Rr]esolve.*, match:float 1