# FreeCAD selector
windowrule = match:class ^(org.freecad.FreeCAD)$, tag +freecad

# FreeCAD splash screen
windowrule = match:tag freecad, match:title ^(FreeCAD)$, tag +freecad-splash,

# FreeCAD main window
windowrule = match:tag freecad, match:initial_title ^(FreeCAD {0-9}.{0-9}.{0-9})$, tag +freecad-main

# FreeCAD popups
windowrule = match:tag freecad, match:title ^(Addon Manager.*), tag +freecad-popup
windowrule = match:tag freecad, match:title ^(Welcome), tag +freecad-popup
windowrule = match:tag freecad, match:title ^(BIM Setup), tag +freecad-popup

# FreeCAD window rules
windowrule = match:tag freecad-splash, center on, no_focus on, border_size 0, float on, no_blur on, no_shadow on
windowrule = match:tag freecad-popup, center on, float on