# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# Launch waybar
# exec-once = ~/.config/hypr/scripts/launchWaybar.sh

# Launch Quickshell
exec-once = quickshell

# Reload plugins and send notification if something goes wrong
exec-once = hyprpm reload -n
# exec-once = hyprctl reload

# Setup XDG for screen sharing
exec-once = ~/.config/hypr/scripts/xdg.sh

# Setup socket2 scripting
exec-once = ~/.config/hypr/scripts/socket2.sh

# Start Polkit
# exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once= systemctl --user start hyprpolkitagent

# Start keyring deamon
# exec-once = /usr/bin/gnome-keyring-daemon --start --components = secrets,pkcs11

# Run hypridle
exec-once = hypridle

# Load Dunst Notification Manager
exec-once = systemctl start --user dunst.service

# Using hyprpaper for wallpaper
exec-once = hyprpaper

# Start OSD service
exec-once = avizo-service

# Setup clipboard
exec-once = wl-clip-persist --clipboard regular

# Load cliphist history
# exec-once = wl-paste --watch cliphist store

# Start easyeffect in the background
# exec-once = easyeffects --gapplication-service
# Start openrgb in the background
# exec-once = openrgb --startminimized --profile "Default"
# Start Blueman
# exec-once = blueman-applet
# Start NetworkManager applet
# exec-once = nm-applet
# Start Element
exec-once = [workspace 11 silent] element-desktop --password-store="gnome-libsecret"
# Start Discord
exec-once = [workspace 11 silent] discord
