exec-once = hyprctl setcursor BreezeX-Dark 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'BreezeX-Dark'

# env = HYPRCURSOR_THEME,BreezeX-Dark
# env = XCURSOR_THEME,BreezeX-Dark
# env = HYPRCURSOR_SIZE,24
# env = XCURSOR_SIZE,24

# No Hardware Cursor
cursor {
    no_hardware_cursors = 2
}