exec-once = hyprctl setcursor Breeze_Default 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Breeze_Default'

# env = HYPRCURSOR_THEME,Breeze_Default
# env = XCURSOR_THEME,Breeze_Default
# env = HYPRCURSOR_SIZE,24
# env = XCURSOR_SIZE,24

# No Hardware Cursor
cursor {
    no_hardware_cursors = 2
}