# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = suppressevent maximize, class:.* # You'll probably like this.

windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = float,class:^(blueman-manager)$
windowrule = float,class:^(nm-connection-editor)$
windowrule = float,class:^(qalculate-gtk)$

# Browser Picture in Picture
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = move 69.5% 4%, title:^(Picture-in-Picture)$

# Hide xwaylandvideobridge windows
windowrule = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrule = noanim,class:^(xwaylandvideobridge)$
windowrule = nofocus,class:^(xwaylandvideobridge)$
windowrule = noinitialfocus,class:^(xwaylandvideobridge)$

# Wine specific
windowrule = float, class:(wineboot.exe)

# Float gamescope windows
windowrule = float, class:(gamescope)

windowrule = workspace 10,class:^(Minecraft.*)$
windowrule = workspace 10,title:^(Minecraft.*)$
windowrule = workspace 10,class:^(minecraft.*)$
windowrule = tile,class:^(Minecraft.*)$
windowrule = tile,class:^(minecraft.*)$
windowrule = tile,title:^(Minecraft.*)$

windowrule = workspace 10, tile,class:^(RuneScape)$
windowrule = workspace 10,class:^(Rs3linux)$

windowrule = workspace 10, tile, maximize,title:^(HDOS .*)$
windowrule = workspace 10,title:^(HDOS)$

windowrule = workspace 10, tile,title:^(RuneLite)$
windowrule = workspace 10,title:^(RuneLite Launcher)$

windowrule = workspace 9,title:^(Bolt Launcher)$

# Move Vesktop to workspace 3
windowrule = workspace 11 silent, class:(fractal)
windowrule = workspace 11 silent, class:(discord)
windowrule = workspace 11 silent, class:(vesktop)

# Move Spotify to workspace 5
windowrule = workspace 12 silent, class:(spotify)
