# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

source = ~/.config/hypr/conf/applications/bitwarden.conf
source = ~/.config/hypr/conf/applications/browser.conf
source = ~/.config/hypr/conf/applications/davinci-resolve.conf
source = ~/.config/hypr/conf/applications/jetbrains.conf
source = ~/.config/hypr/conf/applications/steam.conf
source = ~/.config/hypr/conf/applications/system.conf
source = ~/.config/hypr/conf/applications/terminals.conf

windowrule = suppress_event maximize, match:class .* # You'll probably like this.

windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(qalculate-gtk)$

# Browser Picture in Picture
windowrule = float on, pin on, move ((monitor_w*0.695)) ((monitor_h*0.04)), match:title ^(Picture-in-Picture)$

# Hide xwaylandvideobridge windows
windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

# Wine specific
windowrule = float on, match:class (wineboot.exe)

# Float gamescope windows
windowrule = float on, match:class (gamescope)

windowrule = workspace 10, tile on, match:class ^(Minecraft.*)$
windowrule = workspace 10, tile on, match:title ^(Minecraft.*)$
windowrule = workspace 10, tile on, match:class ^(minecraft.*)$

windowrule = workspace 10, tile on, match:class ^(RuneScape)$
windowrule = workspace 10, match:class ^(Rs3linux)$

windowrule = workspace 10, tile on, maximize on, match:title ^(HDOS .*)$
windowrule = workspace 10, match:title ^(HDOS)$

windowrule = workspace 10, tile on, match:title ^(RuneLite)$
windowrule = workspace 10, match:title ^(RuneLite Launcher)$

windowrule = workspace 9, match:title ^(Bolt Launcher)$

# Move Vesktop to workspace 3
windowrule = workspace 11 silent, match:class (fractal)
windowrule = workspace 11 silent, match:class (discord)
windowrule = workspace 11 silent, match:class (vesktop)

# Move Spotify to workspace 5
windowrule = workspace 12 silent, match:class (spotify)

# Winboat
windowrule = workspace 10, tile on, fullscreen on, match:class (winboat)